### ISSUE TITLE
如何到 native-secret.cpp 中配置 clientId, secret 和应用签名

### ISSUE THREAD

**Issue by willBars** [SamuelGjk/DiyCode#1]
你好：
   半夜看到您写的这个，但是不知道怎么去配置这个clientld , secret ,和应用签名，能否解答下

**Comment by SamuelGjk** [comment]
@willBars 
clientId 和 secret 在 DiyCode 网站创建应用获得，然后在 [native-secret.cpp](https://github.com/SamuelGjk/DiyCode/blob/master/app/src/main/cpp/native-secret.cpp) 文件的最后的这两个方法：
```
jstring Java_moe_yukinoneko_diycode_api_Secret_getClientId(JNIEnv *env, jclass type) {
    return env->NewStringUTF("你自己的 clientId");
}

jstring Java_moe_yukinoneko_diycode_api_Secret_getSecret(JNIEnv *env, jclass type) {
    return env->NewStringUTF("你自己的 secret");
}
```
同时还需要在`static const char *SIGN = "你的应用签名"`配置签名，关于签名验证可以参考这篇文章[Android安全系列之：如何在native层保存关键信息](http://www.jianshu.com/p/2576d064baf1)
